import 'package:nft_marketplace_mobile/domain/entities/nft_collection.dart';

class MockDataService {
  static List<FeaturedNFT> getFeaturedNFTs() {
    return [
      FeaturedNFT(
        id: '1',
        title: 'Memories of Digi...',
        imageUrl: 'assets/images/memories.jpg',
        floor: 0.24,
        isVerified: true,
        backgroundColor: '#4A90E2',
      ),
      FeaturedNFT(
        id: '2',
        title: 'Pixel - Farm Land...',
        imageUrl: 'assets/images/memories.jpg',
        floor: 1,
        isVerified: true,
        backgroundColor: '#9013FE',
      ),
      FeaturedNFT(
        id: '1',
        title: 'Memories of Digi...',
        imageUrl: 'assets/images/memories.jpg',
        floor: 0.24,
        isVerified: true,
        backgroundColor: '#4A90E2',
      ),
      FeaturedNFT(
        id: '2',
        title: 'Pixel - Farm Land...',
        imageUrl: 'assets/images/memories.jpg',
        floor: 1,
        isVerified: true,
        backgroundColor: '#9013FE',
      ),
      FeaturedNFT(
        id: '1',
        title: 'Memories of Digi...',
        imageUrl: 'assets/images/memories.jpg',
        floor: 0.24,
        isVerified: true,
        backgroundColor: '#4A90E2',
      ),
      FeaturedNFT(
        id: '2',
        title: 'Pixel - Farm Land...',
        imageUrl: 'assets/images/memories.jpg',
        floor: 1,
        isVerified: true,
        backgroundColor: '#9013FE',
      ),
    ];
  }

  static List<NFTCollection> getTrendingCollections() {
    return [
      NFTCollection(
        id: '1',
        name: 'Courtyard.io',
        imageUrl: 'assets/images/memories.jpg',
        floor: 18,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
        currency: 'MATIC',
      ),
      NFTCollection(
        id: '2',
        name: 'egg',
        imageUrl: 'assets/images/memories.jpg',
        floor: 0.2,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
      ),
      NFTCollection(
        id: '1',
        name: 'Courtyard.io',
        imageUrl: 'assets/images/memories.jpg',
        floor: 18,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
        currency: 'MATIC',
      ),
      NFTCollection(
        id: '2',
        name: 'egg',
        imageUrl: 'assets/images/memories.jpg',
        floor: 0.2,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
      ),
      NFTCollection(
        id: '1',
        name: 'Courtyard.io',
        imageUrl: 'assets/images/memories.jpg',
        floor: 18,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
        currency: 'MATIC',
      ),
      NFTCollection(
        id: '2',
        name: 'egg',
        imageUrl: 'assets/images/memories.jpg',
        floor: 0.2,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
      ),
      NFTCollection(
        id: '1',
        name: 'Courtyard.io',
        imageUrl: 'assets/images/memories.jpg',
        floor: 18,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
        currency: 'MATIC',
      ),
      NFTCollection(
        id: '2',
        name: 'egg',
        imageUrl: 'assets/images/memories.jpg',
        floor: 0.2,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
      ),
      NFTCollection(
        id: '1',
        name: 'Courtyard.io',
        imageUrl: 'assets/images/memories.jpg',
        floor: 18,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
        currency: 'MATIC',
      ),
      NFTCollection(
        id: '2',
        name: 'egg',
        imageUrl: 'assets/images/memories.jpg',
        floor: 0.2,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
      ),
      NFTCollection(
        id: '1',
        name: 'Courtyard.io',
        imageUrl: 'assets/images/memories.jpg',
        floor: 18,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
        currency: 'MATIC',
      ),
      NFTCollection(
        id: '2',
        name: 'egg',
        imageUrl: 'assets/images/memories.jpg',
        floor: 0.2,
        volume: 28.1,
        changePercentage: -22.37,
        isVerified: true,
      ),
    ];
  }
}
